services:
  # Backend Service
  - type: web
    name: poll-system-backend
    env: node
    plan: free
    nodeVersion: 18
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://sonyshaik027:S0ny027%40@cluster0.zitqgzq.mongodb.net/livepolling?retryWrites=true&w=majority&appName=Cluster0
    healthCheckPath: /
    
  # Frontend Service  
  - type: web
    name: poll-system-frontend
    env: node
    plan: free
    nodeVersion: 20
    rootDir: client
    buildCommand: npm ci && npm run build
    startCommand: npm run serve
    envVars:
      - key: NODE_ENV
        value: production
      - key: REACT_APP_SERVER_URL
        value: https://poll-system-backend-8j3s.onrender.com
    healthCheckPath: /
